version: '3.8'

services:
  backend:
    build: ./calculator-backend
    ports:
      - "8080:8080"
    networks:
      - app-network

  frontend:
    build: ./calculator-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
