name: Docker Build and Push

on:
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push calculator-frontend image
        uses: docker/build-push-action@v3
        with:
          context: ./calculator-frontend  # Context is the directory containing Dockerfile and related files
          file: ./calculator-frontend/Dockerfile
          platforms: linux/amd64
          push: true
          tags: hughnguyen/calculator-frontend:latest

      - name: Build and push calculator-backend image
        uses: docker/build-push-action@v3
        with:
          context: ./calculator-backend  # Make sure this is the correct relative path to the backend Docker context
          file: ./calculator-backend/Dockerfile
          platforms: linux/amd64
          push: true
          tags: hughnguyen/calculator-backend:latest
