name: Setup EKS

on:
  workflow_dispatch:

jobs:
  install-load-balancer-controller:
    name: Install AWS Load Balancer Controller
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      
      - name: Update kubeconfig
        run: |
          aws eks update-kubeconfig --region $AWS_REGION --name $CLUSTER_NAME
        env:
          CLUSTER_NAME: ${{ secrets.CLUSTER_NAME }}

      - name: Install kubectl
        run: |
          curl -LO "https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl"
          chmod +x ./kubectl
          sudo mv ./kubectl /usr/local/bin/kubectl

      - name: Install helm
        run: |
          curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3
          chmod 700 get_helm.sh
          ./get_helm.sh

      - name: Add EKS chart repo to Helm
        run: |
          helm repo add eks https://aws.github.io/eks-charts

      - name: Update Helm repositories
        run: |
          helm repo update

      - name: Install AWS Load Balancer Controller
        run: |
          helm upgrade --install aws-load-balancer-controller eks/aws-load-balancer-controller \
            --set clusterName=$CLUSTER_NAME \
            --set serviceAccount.create=false \
            --set serviceAccount.name=aws-load-balancer-controller \
            --namespace kube-system \
            --version=1.6.2
        env:
          CLUSTER_NAME: ${{ secrets.CLUSTER_NAME }}

      - name: Verify installation
        run: |
          kubectl get deployment -n kube-system aws-load-balancer-controller
